main:
  clusterGroupName: datacenter

global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  imageregistry:
    account: mcarioli
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: mauriziocarioli
    #username: PLAINTEXT
    email: maurizio.carioli@gmail.com
    dev_revision: main

  s3:
    bucket:
      name: edge9
      region: us-east-1
      message:
        aggregation:
          count: 50
      custom:
        endpoint:
          enabled: false
